name: Technical Design Document
description: Collaborative technical design for approved features
title: "[DESIGN] "
labels: ["technical-design", "step-1-analysis"]
body:
  - type: input
    attributes:
      label: Related Feature Request
      description: "Link to the feature request issue (#number)"
      placeholder: "#123"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Complexity Assessment
      options:
        - "1 - Simple (< 5 files changed)"
        - "2 - Moderate (5-15 files changed)"
        - "3 - Complex (15+ files, new dependencies)"
        - "4 - High (architectural changes)"
        - "5 - Critical (breaking changes)"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Design Process Checklist
      value: |
        ## Design Process Steps
        - [ ] **Step 1**: Requirements Analysis & Scope Definition
        - [ ] **Step 2**: Data Model Design
        - [ ] **Step 3**: API Design & Integration Points
        - [ ] **Step 4**: Frontend Architecture & Components
        - [ ] **Step 5**: Technology Stack & Dependencies
        - [ ] **Step 6**: Testing Strategy
        - [ ] **Step 7**: Implementation Plan & Task Breakdown
        - [ ] **Step 8**: Deployment & Infrastructure Plan
        - [ ] **Step 9**: Design Review & Approval
        
        ---
        
        ## Current Step: Requirements Analysis
        *This section will be updated as we progress through each step*
        
        ### Step 1: Requirements Analysis & Scope Definition
        [This will be filled during the design process - analyze feature request, clarify ambiguities, define clear boundaries]
        
        ### Step 2: Data Model Design
        [To be completed - database schema, data relationships, storage strategy]
        
        ### Step 3: API Design & Integration Points
        [To be completed - REST/GraphQL endpoints, request/response schemas, authentication]
        
        ### Step 4: Frontend Architecture & Components
        [To be completed - component hierarchy, state management, user flow design]
        
        ### Step 5: Technology Stack & Dependencies
        [To be completed - technology choices, new dependencies, version compatibility]
        
        ### Step 6: Testing Strategy
        [To be completed - unit, integration, e2e test approaches]
        
        ### Step 7: Implementation Plan & Task Breakdown
        [To be completed - break design into implementable tasks, estimate complexity, identify dependencies]
        
        ### Step 8: Deployment & Infrastructure Plan
        [To be completed - deployment strategy, infrastructure changes, rollback procedures]
        
        ### Step 9: Design Review & Approval
        [To be completed - final review of all sections for consistency and completeness]